sudo: false
language: c

addons:
  apt:
    packages:
      - luarocks
      - pandoc

install: luarocks install --local luacheck
before_script: $HOME/.luarocks/bin/luacheck . -q
script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh -o release.sh
  - bash release.sh
